### ISSUE TITLE
failing to install package

### ISSUE THREAD

**Issue by lawrencelby** [tye27/RobinCar#1]
Hello, I am Lawrence.
I would like to work with your RobinCar package but it is failing to install. I am using R version 4.1.0 I get the following warning

Warning in install.packages :
  package ‘RobinCar’ is not available for this version of R

Do you have some advice for this?
Thanks

**Comment by tye27** [comment]
Can you try the following code to install?

library(devtools)
install_github("tye27/RobinCar")

**Comment by lawrencelby** [comment]
Thanks Ye,
I overcame the problem by using the following code

devtools::install_dev("remotes")
library(devtools)
install_github("tye27/RobinCar")
